---
########
# Argmap config data
# For use in lua code, layouts and scripts.
# This file is not considered part of a public API and can change at any time without being considered BREAKING.
# Copyright 2022 Michael Hayes
# SPDX - License - Identifier: MIT
########

# Argmap document metadata
DEFAULT_LANGUAGE: en
FILE_TEMPLATE_HTML_DEFAULT: ${FILE_TEMPLATE_HTML_ARGMAP_MAIN}
PATH_INCLUDES_ARGMAP_CONTAINER_DEFAULT: ${PATH_INCLUDES_MAPJS_CONTAINER_STANDARD}
PANDOC_FILTER_LUA_DEFAULT: ${PATH_FILE_PANDOC_FILTER_LUA_ARGMAP}
DEFAULT_MAPJS_CSS: /mapjs-default-styles.css

# All CSS files used by html output.
#   However, pandoc templates won't expand the variables
#   , so need to reference anchor earlier in same doc instead.
css: # Default pandoc template value
  - ${DEFAULT_MAPJS_CSS}


# DEPRECATED:
PATH_CONVERT_LOCAL: ${PATH_PROFILE_LOCAL}/bin/convert
PATH_DIR_PUBLIC: ${PATH_DIR_MAPJS_ROOT}/${DIR_PUBLIC}

...
