name: argmap
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anaconda/linux-64::luarocks==3.7.0=lua53h06a4308_0
  - texlive-core
  - pandoc=2.9.2.1
  - imagemagick
  - conda-forge/linux-64::unzip==6.0=h7f98852_3
  - anaconda/linux-64::yaml==0.2.5=h7b6447c_0
  - anaconda/linux-64::nodejs==16.13.1=hb931c9a_0
  - anaconda/linux-64::lua==5.3.4=h7b6447c_0
variables:
  CONDA_ENV_ARGMAP: argmap
prefix: /opt/miniconda3/envs/argmap
