---
########
# Pandoc defaults file - for pre-processing config files
# Copyright 2022 Michael Hayes
# SPDX - License - Identifier: MIT
########

to: plain
from: markdown-tex_math_dollars 
# template: config/environment-argmap.yaml
# output-file: config/environment-argmap-processed.yaml
metadata-files:
  - config/environment-argmap.yaml
  - config/config-argmap-paths.yaml
  - config/config-argmap.yaml
  - mapjs/config/environment-mapjs.yaml
  - mapjs/config/config-mapjs-paths.yaml
  - mapjs/config/config-mapjs.yaml
  - config/processed/environment-argmap-processed.yaml

...
